
providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1679356985'

[variables]
NIXPACKS_PYTHON_VERSION = '3.10'
NIXPACKS_METADATA = 'python,poetry'
NIXPACKS_POETRY_VERSION = '1.3.1'
PYTHONUNBUFFERED = '1'
[phases.install]
dependsOn = ['setup']
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install poetry==$NIXPACKS_POETRY_VERSION && poetry install --no-dev --no-interaction --no-ansi']
cacheDirectories = ['/root/.cache/pip']
paths = ['/opt/venv/bin']

[phases.setup]
nixPkgs = [
    'python310',
    'gcc',
    'poetry'
]
nixLibs = [
    'zlib',
    'stdenv.cc.cc.lib',
]
nixOverlays = []
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'

[start]
cmd = 'make start'
